import { ArrowDown, ArrowRight, ArrowUpRight, CarFront, Check, Camera, MessageCircle, Search, ShieldCheck, SlidersHorizontal, MapPin, Camera as Instagram, KeyRound } from 'lucide-react';
import { Process } from '@/components/nero/process';
import { Navigation } from '@/components/nero/navigation';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
const instagram = 'https://www.instagram.com/nero.automoviles/';
export default function Home() {
return <><Navigation/><main id="contenido">
<section className="hero" aria-labelledby="hero-title"><div className="hero-image" aria-hidden="true" style={{backgroundImage: `url(${process.env.GITHUB_PAGES === 'true' ? '/nero-automoviles' : ''}/images/nero-hero.webp)`}}/><div className="hero-shade"/><div className="container hero-content"><p className="eyebrow"><span className="status-dot"/> COMPRA · VENTA · BÚSQUEDA</p><h1 id="hero-title">Tu próximo auto.<br/>Tu próximo <span>paso.</span></h1><p className="hero-description">Encontrá tu próximo auto.<br/>Vendé el tuyo sin complicaciones.</p><p className="hero-note">Conectamos compradores y vendedores<br className="desktop-break"/> de vehículos en todo Uruguay.</p><div className="button-row"><a className="button button-light" href="#vende">Vender mi auto <ArrowUpRight size={19}/></a><a className="button button-outline" href="#vehiculos">Ver vehículos <ArrowRight size={18}/></a></div></div><div className="container hero-bottom"><span><MapPin size={14}/> EN TODO URUGUAY</span><span className="hero-caption">Imagen editorial · No corresponde al catálogo</span><a href="#servicios" aria-label="Descubrir servicios"><ArrowDown size={20}/></a></div></section>
<section id="servicios" className="services container" aria-label="Nuestros servicios">{[{n:'01',title:'Comprá.',description:'El próximo capítulo empieza con el auto indicado.',link:'Explorar vehículos',href:'#vehiculos',icon:CarFront},{n:'02',title:'Vendé.',description:'Tu auto sigue con vos. Nosotros nos ocupamos de la gestión.',link:'Vender con NERO',href:'#vende',icon:KeyRound},{n:'03',title:'Encontrá.',description:'Contanos qué buscás. Te ayudamos a encontrarlo.',link:'Buscar mi próximo auto',href:'#encontra',icon:Search}].map(({n,title,description,link,href,icon:Icon})=><a className="service" href={href} key={n}><div className="service-top"><span>{n} /</span><Icon size={25} strokeWidth={1.3}/></div><h2>{title}</h2><p>{description}</p><span className="text-link">{link}<ArrowUpRight size={18}/></span></a>)}</section>
<section id="vende" className="sell-section section-space"><div className="container sell-grid"><div><p className="eyebrow muted">TU AUTO. NUESTRA GESTIÓN.</p><h2 className="section-title">Vos tenés el auto.<br/><span>Nosotros, el enfoque.</span></h2><p className="body-copy">¿Querés vender tu auto? Nosotros te ayudamos. Nos encargamos de conectar tu vehículo con las personas que lo están buscando.</p><a className="button button-light" href={instagram} target="_blank" rel="noreferrer">Quiero vender con NERO <ArrowUpRight size={18}/></a><span className="contact-note">Hablemos por Instagram · @nero.automoviles</span></div><div className="sell-benefits">{[{icon:Camera,title:'Una presentación que hace la diferencia',text:'Preparamos la publicación y la presentación profesional de tu vehículo.'},{icon:MessageCircle,title:'Menos consultas. Más posibilidades.',text:'Atendemos consultas, filtramos interesados y damos difusión a tu auto.'},{icon:ShieldCheck,title:'Acompañamiento en cada paso',text:'Coordinamos entre las partes y te acompañamos durante la negociación.'}].map(({icon:Icon,title,text})=><div className="benefit" key={title}><span className="icon-box"><Icon size={22} strokeWidth={1.4}/></span><div><h3>{title}</h3><p>{text}</p></div></div>)}<div className="owner-note"><KeyRound size={20}/><p><strong>Tu auto se queda con vos.</strong><br/>El vehículo permanece con su propietario mientras buscamos interesados.</p></div></div></div></section>
<section id="vehiculos" className="catalog-section section-space container"><div className="section-heading"><div><p className="eyebrow muted">EL AUTO INDICADO, A TU ALCANCE</p><h2 className="section-title">Nuestro catálogo.</h2></div><span className="availability"><span className="status-dot"/> PRÓXIMAMENTE</span></div><Empty className="catalog-empty"><EmptyHeader className="empty-inner"><span className="empty-icon"><CarFront size={34} strokeWidth={1}/></span><EmptyTitle className="empty-title">El primer paso ya está en marcha.</EmptyTitle><EmptyDescription className="empty-description">Estamos incorporando nuestros primeros vehículos.<br/>El tuyo puede ser parte de lo que viene.</EmptyDescription></EmptyHeader><a className="text-link" href="#vende">¿Querés vender el tuyo? <ArrowUpRight size={19}/></a></Empty><p className="catalog-disclosure"><ShieldCheck size={15}/> Los vehículos publicados pertenecen a sus propietarios. NERO gestiona su comercialización.</p></section>
<section id="encontra" className="search-section container"><div className="search-symbol" aria-hidden="true"><Search size={58} strokeWidth={.7}/></div><div><p className="eyebrow muted">LO QUE BUSCÁS, IMPORTA</p><h2>Tu próximo auto.<br/>A tu medida.</h2><p>Contanos qué estás buscando y nosotros buscamos<br className="desktop-break"/> opciones que se adapten a vos.</p><div className="preferences"><span><CarFront size={15}/> Vehículo</span><span><SlidersHorizontal size={15}/> Presupuesto</span><span><MapPin size={15}/> Ubicación</span></div></div><a className="button button-light" href={instagram} target="_blank" rel="noreferrer">Empezar mi búsqueda <ArrowUpRight size={18}/></a></section>
<section id="como-funciona" className="process-section section-space container"><div className="section-heading"><div><p className="eyebrow muted">SIMPLE, DE PRINCIPIO A FIN</p><h2 className="section-title">Un camino claro.</h2></div><p className="heading-note">Sin vueltas. Con alguien<br/>que te acompaña.</p></div><Process/></section>
<section className="trust-section"><div className="container trust-grid"><p className="eyebrow">ESTO ES NERO</p><div><h2>Una forma diferente<br/>de comprar y vender autos.</h2><p>Somos una propuesta de intermediación digital. Conectamos personas, cuidamos la información y hacemos que cada paso sea más claro.</p><div className="trust-values">{['Información transparente','Atención personalizada','Privacidad del propietario'].map(t=><span key={t}><Check size={16}/>{t}</span>)}</div></div></div></section>
<section id="contacto" className="contact-section container"><div><p className="eyebrow muted">CONVERSEMOS</p><h2>Todo empieza<br/>con un <span>hola.</span></h2></div><div className="contact-right"><p>¿Vendés, comprás o todavía estás buscando?<br/>Contanos. Estamos para ayudarte.</p><a href={instagram} className="instagram-link" target="_blank" rel="noreferrer"><Instagram size={23}/> @nero.automoviles <ArrowUpRight size={25}/></a></div></section>
</main><footer className="footer container"><a href="#" className="wordmark" aria-label="NERO Automóviles, inicio"><strong>NERO</strong><span>AUTOMÓVILES</span></a><p>Tu auto. Nuestra gestión.</p><span>Uruguay · {new Date().getFullYear()}</span><a href={instagram} target="_blank" rel="noreferrer" aria-label="Instagram de NERO"><Instagram size={20}/></a></footer></>;
}



