import { getBindings } from '@/db';
import { enforceRateLimit } from '@/lib/rate-limit';
import { assertHoneypot,assertSameOrigin,email,integer,optional,phone,required } from '@/validators/requests';
export const runtime='edge';
const MAX_FILES=12,MAX_FILE_SIZE=3*1024*1024,MAX_TOTAL=24*1024*1024;
function validImage(bytes:Uint8Array,type:string){if(type==='image/jpeg')return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(type==='image/png')return bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47;if(type==='image/webp')return new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';return false}
export async function POST(request:Request){const stored:string[]=[];try{assertSameOrigin(request);await enforceRateLimit(request,'seller');const len=Number(request.headers.get('content-length')??0);if(len>MAX_TOTAL+1024*1024)throw new Error('La carga supera el máximo permitido.');const form=await request.formData();assertHoneypot(form);if(form.get('terms')!=='on')throw new Error('Necesitamos que aceptes las condiciones para continuar.');const files=form.getAll('images').filter((v):v is File=>v instanceof File&&v.size>0);if(files.length>MAX_FILES)throw new Error(`Podés adjuntar hasta ${MAX_FILES} fotos.`);if(files.reduce((n,f)=>n+f.size,0)>MAX_TOTAL)throw new Error('Las fotos superan el límite total de 24 MB.');const now=new Date().toISOString(),id=crypto.randomUUID();const {db,files:bucket}=getBindings();const imageRows:unknown[][]=[];
for(let i=0;i<files.length;i++){const file=files[i];if(file.size>MAX_FILE_SIZE)throw new Error(`La foto ${i+1} supera 3 MB.`);const bytes=new Uint8Array(await file.arrayBuffer());if(!validImage(bytes,file.type))throw new Error(`La foto ${i+1} no es JPEG, PNG o WebP válido.`);const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp';const key=`private/seller/${id}/${crypto.randomUUID()}.${ext}`;await bucket.put(key,bytes,{httpMetadata:{contentType:file.type}});stored.push(key);imageRows.push([crypto.randomUUID(),id,key,file.type,file.size,i,now])}
const statements=[db.prepare('INSERT INTO seller_requests (id,name,phone,email,department,city,brand,model,version,year,mileage,fuel,transmission,engine,color,doors,asking_price,currency,condition,description,status,terms_version,terms_accepted_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,required(form,'name','tu nombre'),phone(form),email(form),required(form,'department','el departamento'),required(form,'city','la ciudad'),required(form,'brand','la marca'),required(form,'model','el modelo'),optional(form,'version'),integer(form,'year','El año',1900,new Date().getFullYear()+1),integer(form,'mileage','El kilometraje',0,2000000),required(form,'fuel','el combustible'),required(form,'transmission','la transmisión'),optional(form,'engine'),optional(form,'color'),integer(form,'doors','La cantidad de puertas',2,6,true),integer(form,'askingPrice','El precio',0,100000000,true),'USD',required(form,'condition','el estado general'),required(form,'description','la descripción',3000),'NUEVA','2026-09-08',now,now,now),...imageRows.map(r=>db.prepare('INSERT INTO seller_request_images (id,request_id,object_key,content_type,size,position,created_at) VALUES (?,?,?,?,?,?,?)').bind(...r))];await db.batch(statements);return Response.json({ok:true,id},{status:201})}catch(error){if(stored.length){try{await getBindings().files.delete(stored)}catch{}}return Response.json({ok:false,error:error instanceof Error?error.message:'No pudimos recibir tu vehículo.'},{status:400})}}
